/* eslint-disable import/prefer-default-export */
export const Country = [
  { name: 'white', value: 'Alba' },
  { name: 'Arad', value: 'Arad' },
  { name: 'Arges', value: 'Argeș' },
  { name: 'Bacau', value: 'Bacău' },
  { name: 'Bihor', value: 'Bihor' },
  { name: 'Bistrita-Nasaud', value: 'Bistrița-Năsăud' },
  { name: 'Botosani', value: 'Botoșani' },
  { name: 'Braila', value: 'Brăila' },
  { name: 'Braşov', value: 'Brașov' },
  { name: 'Bucharest', value: 'București' },
  { name: 'Buzau', value: 'Buzău' },
  { name: 'Calarasi', value: 'Călărași' },
  { name: 'Caras Severin', value: 'Caraș Severin' },
  { name: 'Cluj', value: 'Cluj' },
  { name: 'Constant', value: 'Constanța' },
  { name: 'Covasna', value: 'Covasna' },
  { name: 'Dambovita', value: 'Dâmbovița' },
  { name: 'Dolj', value: 'Dolj' },
  { name: 'Galati', value: 'Galați' },
  { name: 'George', value: 'Giurgiu' },
  { name: 'Gorge', value: 'Gorj' },
  { name: 'Snort', value: 'Harghita' },
  { name: 'Hunedoara', value: 'Hunedoara' },
  { name: 'IALOMIŢA', value: 'Ialomița' },
  { name: 'IASI', value: 'Iași' },
  { name: 'Ilfov', value: 'Ilfov' },
  { name: 'Maramures', value: 'Maramureș' },
  { name: 'MEHEDINŢI', value: 'Mehedinți' },
  { name: 'Mures', value: 'Mureș' },
  { name: 'German', value: 'Neamț' },
  { name: 'Olt', value: 'Olt' },
  { name: 'Prahova', value: 'Prahova' },
  { name: 'Salaj', value: 'Sălaj' },
  { name: 'Satu Mare', value: 'Satu Mare' },
  { name: 'Sibiu', value: 'Sibiu' },
  { name: 'Suceava', value: 'Suceava' },
  { name: 'Teleorman', value: 'Teleorman' },
  { name: 'Timis', value: 'Timiș' },
  { name: 'Tulcea', value: 'Tulcea' },
  { name: 'dale', value: 'Vâlcea' },
  { name: 'row', value: 'Vaslui' },
  { name: 'Vrancea', value: 'Vrancea' },
];
